import os

os.makedirs("knowledge_base", exist_ok=True)

docs = {
    "Xarn_Velgor.md": """# Xarn Velgor

## Overview
Xarn Velgor is the supreme leader of the Dominion Authority and one of the most powerful Void Masters in known history. Once a promising Flux Guardian, he fell to the Void Path and became the enforcer of Lord Malachar's will.

## Background
Originally known as a talented Flux-sensitive warrior, Xarn was seduced by the promise of unlimited power through the Void Path. After a tragic loss, he surrendered to darkness and was reborn as Xarn Velgor, clad in black armor that sustains his damaged form.

## Abilities
- Master of the Plasma Blade
- Profound connection to the Void Path
- Strategic genius and military commander
- Ability to sense Flux disturbances across star systems

## Notable Actions
- Led the assault on the Freedom Coalition headquarters
- Hunted down Flux Wardens across the galaxy
- Commanded the Void Core superweapon
- Final confrontation with his son, Kael Torren

## Relationships
- **Lord Malachar**: Master and Emperor
- **Kael Torren**: Son and eventual redeemer
- **Orin Kestrel**: Former mentor
- **Lyra Solari**: Former ally turned enemy
""",
    "Kael_Torren.md": """# Kael Torren

## Overview
Kael Torren is a Flux-sensitive hero who rose from a humble background on Aridus Prime to become one of the most powerful Flux Guardians in history. He is the son of Xarn Velgor.

## Early Life
Born on Aridus Prime, Kael grew up as an orphan, unaware of his true parentage. He dreamed of becoming a pilot. His destiny changed when he discovered Unit-7, carrying a message from Orin Kestrel.

## Journey
- Discovered his Flux-sensitivity under Orin Kestrel's guidance
- Joined the Freedom Coalition
- Trained as a Flux Guardian
- Confronted his father, Xarn Velgor
- Redeemed his father and destroyed Lord Malachar

## Abilities
- Exceptional pilot and marksman
- Powerful connection to the Radiant Path
- Skilled Plasma Blade wielder
- Natural leader
""",
    "Lyra_Solari.md": """# Lyra Solari

## Overview
Lyra Solari is the leader of the Freedom Coalition and a key figure in the resistance against the Dominion Authority. A former royal princess of Alderis Prime.

## Background
Lyra was raised as a princess on Alderis Prime. When the Dominion Authority destroyed her homeworld, she joined the Freedom Coalition and quickly rose to leadership.

## Role in the Resistance
- Organized the theft of the Void Core schematics
- Led the assault on the first Void Core
- Coordinated guerrilla operations across the galaxy

## Skills
- Expert tactician and strategist
- Skilled diplomat and negotiator
- Proficient with blaster pistols
""",
    "Void_Core.md": """# Void Core

## Overview
The Void Core is a massive space station and superweapon capable of destroying entire planets. Built by the Dominion Authority.

## Specifications
- Diameter: 160 kilometers
- Crew: 1.2 million personnel
- Weapon: Void Energy Beam powered by synthetic dark matter

## History
The Void Core was designed to enforce the Dominion Authority's rule through fear. Its first use was the destruction of Alderis Prime.

## Weaknesses
Despite its power, the Void Core had a critical vulnerability: a small thermal exhaust port leading directly to the main reactor.
""",
    "Plasma_Blade.md": """# Plasma Blade

## Overview
The Plasma Blade is an elegant weapon for a more civilized age. An energy sword powered by a kyber crystal, it is the signature weapon of Flux Wardens and Void Disciples.

## Construction
- Hilt: Customized to the wielder
- Blade: Plasma loop contained by magnetic field
- Power source: Kyber crystal
- Colors: Blue, green (Wardens), red (Void Disciples)

## Combat Forms
There are seven forms of Plasma Blade combat, from basic Shii-Cho to aggressive Juyo/Vaapad.
""",
    "Synth_Flux.md": """# Synth Flux

## Overview
The Synth Flux is a metaphysical and ubiquitous energy field that binds the galaxy together. Generated by all living things.

## The Two Paths
- **Radiant Path**: Compassion, healing, defense, knowledge
- **Void Path**: Fear, anger, hatred, aggression

## Abilities
- Telekinesis
- Mind tricks
- Precognition
- Enhanced reflexes
""",
    "Freedom_Coalition.md": """# Freedom Coalition

## Overview
The Freedom Coalition is a resistance movement fighting to restore democracy and freedom to the galaxy. Opposed to the Dominion Authority's tyranny.

## Major Operations
- Stealing the Void Core plans
- Battle of the Void Core
- Battle of Cryoplan
- Battle of Verdantis
- Assault on Nexus Prime

## Victory
The Freedom Coalition triumphed when Kael Torren redeemed Xarn Velgor and destroyed Lord Malachar.
""",
    "Dominion_Authority.md": """# Dominion Authority

## Overview
The Dominion Authority is a tyrannical regime that replaced the Galactic Republic. Led by Emperor Lord Malachar.

## Government Structure
- Emperor: Lord Malachar
- Imperial Ruling Council
- Moffs: Regional governors

## Military
- Imperial Army
- Imperial Navy
- Shadow Troopers
- Imperial Intelligence
""",
    "Aridus_Prime.md": """# Aridus Prime

## Overview
Aridus Prime is a harsh desert planet located in the Outer Rim Territories. Known for its twin suns, endless dunes, and moisture farming communities.

## Geography
- Terrain: Endless desert with rocky canyons
- Climate: Extremely hot and arid
- Notable locations: Dusthaven, Obi-Wan's Cave

## Role in the War
Aridus Prime served as the starting point for Kael Torren's journey.
""",
    "Cryoplan.md": """# Cryoplan

## Overview
Cryoplan is an ice planet located in the Hoth system. A remote and inhospitable world, it served as the main base of operations for the Freedom Coalition.

## Geography
- Terrain: Frozen wasteland, ice mountains
- Climate: Sub-zero temperatures
- Notable locations: Echo Base

## The Battle of Cryoplan
The Dominion Authority discovered Echo Base through probe droids. Xarn Velgor led an assault with AT-AT walkers.
""",
    "Verdantis.md": """# Verdantis

## Overview
Verdantis is a forested moon orbiting the gas giant Pantora Prime. Home to the native Ewok species.

## The Shield Generator
The Dominion Authority constructed a shield generator on Verdantis to protect the second Void Core.

## The Battle of Verdantis
The Freedom Coalition launched a two-pronged attack to destroy the shield generator and the Void Core.
""",
    "Nexus_Prime.md": """# Nexus Prime

## Overview
Nexus Prime is the capital world of the Dominion Authority and the center of galactic government. An ecumenopolis.

## Imperial Palace
The Imperial Palace sits atop a mountain in the governmental district. It was transformed into Lord Malachar's throne room.

## Role in the War
Nexus Prime served as the political and military center of the Dominion Authority.
""",
    "Jax_Maverick.md": """# Jax Maverick

## Overview
Jax Maverick is a rogue pilot, smuggler, and reluctant hero who became a key figure in the Freedom Coalition.

## The Star Runner
Jax's ship, the Star Runner, is a modified YT-1300 freighter known for its speed.

## Role in the War
- Transported Kael Torren across the galaxy
- Participated in the Battle of the Void Core
- Led smuggling operations
""",
    "Orin_Kestrel.md": """# Orin Kestrel

## Overview
Orin Kestrel is a legendary Flux Guardian and mentor to Kael Torren. One of the last surviving members of the Order of Wardens.

## Background
Orin was a respected Flux Guardian who fought in the Clone Wars. After the rise of the Dominion Authority, he went into hiding on Aridus Prime.

## Legacy
Orin Kestrel's wisdom and sacrifice inspired a new generation of Flux Wardens.
""",
    "Master_Vexis.md": """# Master Vexis

## Overview
Master Vexis is a legendary Flux Guardian and the grandmaster of the Order of Wardens. Despite his small stature, he is one of the most powerful Flux-sensitives in history.

## Background
Master Vexis has trained Flux Guardians for centuries, with over 900 years of wisdom.

## Notable Quotes
"Do or do not. There is no try."
""",
    "Lord_Malachar.md": """# Lord Malachar

## Overview
Lord Malachar is the Emperor of the Dominion Authority and the master of Xarn Velgor. A master of the Void Path.

## Rise to Power
- Manipulated the Galactic Senate for decades
- Orchestrated the Clone Wars
- Executed Order 66
- Declared himself Emperor

## Downfall
Lord Malachar was ultimately defeated when Xarn Velgor redeemed himself.
""",
    "Brakk.md": """# Brakk

## Overview
Brakk is a massive Brakkan species warrior and loyal companion to Jax Maverick.

## Characteristics
- Height: 2.3 meters
- Species: Brakkan
- Weapons: Bowcaster crossbow
- Skills: Expert pilot, mechanic, and warrior
""",
    "Unit_7.md": """# Unit-7

## Overview
Unit-7 is an R2-series astromech droid who played a crucial role in the galactic civil war.

## Role in the War
- Carried the Void Core schematics
- Accompanied Kael Torren throughout his journey
- Repaired ships and equipment in critical moments
""",
    "Protocol_Bot.md": """# Protocol-Bot

## Overview
Protocol-Bot is a C-3PO protocol droid fluent in over six million forms of communication.

## Specifications
- Model: C-3PO protocol droid
- Height: 1.71 meters
- Languages: Over 6 million forms of communication
""",
    "Interceptor_7.md": """# Interceptor-7

## Overview
The Interceptor-7, also known as the X-Wing starfighter, is the primary starfighter of the Freedom Coalition.

## Specifications
- Manufacturer: Incom Corporation
- Length: 12.5 meters
- Crew: 1 pilot + 1 astromech droid
- Armament: 4 laser cannons, 2 proton torpedo launchers
""",
    "Shadow_Drone.md": """# Shadow Drone

## Overview
The Shadow Drone, also known as the TIE Fighter, is the primary starfighter of the Dominion Authority.

## Specifications
- Manufacturer: Sienar Fleet Systems
- Length: 6.4 meters
- Crew: 1 pilot
- Armament: 2 laser cannons
- Shields: None
""",
    "Star_Runner.md": """# Star Runner

## Overview
The Star Runner, also known as the Millennium Falcon, is a modified YT-1300 light freighter captained by Jax Maverick.

## Specifications
- Model: YT-1300 light freighter
- Length: 34.75 meters
- Crew: 2
- Hyperdrive: Class 0.5 (exceptionally fast)
""",
    "Shadow_Trooper.md": """# Shadow Trooper

## Overview
Shadow Troopers, also known as Stormtroopers, are the elite infantry of the Dominion Authority.

## Equipment
- White plastoid armor
- E-11 blaster rifle
- Thermal detonators
- Comms systems
""",
    "Flux_Wardens.md": """# Flux Wardens

## Overview
The Flux Wardens were peacekeepers and guardians of justice in the Galactic Republic for over a thousand generations.

## The Jedi Code
"There is no emotion, there is peace.
There is no ignorance, there is knowledge."

## The Purge
Lord Malachar executed Order 66, purging the Flux Wardens.
""",
    "Void_Disciples.md": """# Void Disciples

## Overview
The Void Disciples are dark side practitioners who seek power through the Void Path.

## The Sith Code
"Peace is a lie, there is only passion.
Through passion, I gain strength."

## The Rule of Two
Only two Sith—master and apprentice.
""",
    "Order_66.md": """# Order 66

## Overview
Order 66 was a secret protocol embedded in clone troopers' inhibitor chips, commanding them to execute their Flux Warden generals.

## The Execution
Lord Malachar contacted clone commanders with the command: "Execute Order 66."

## Legacy
Order 66 represents the ultimate betrayal.
""",
    "Clone_Wars.md": """# Clone Wars

## Overview
The Clone Wars were a galaxy-wide conflict between the Galactic Republic and the Confederacy of Independent Systems.

## The Clone Army
- Cloned from bounty hunter Jango Fett
- Trained on Kamino
- Programmed with inhibitor chips
""",
    "Alderis_Prime.md": """# Alderis Prime

## Overview
Alderis Prime is a beautiful, peaceful planet known for its lush landscapes. The homeworld of Lyra Solari.

## Destruction
Lord Malachar ordered the destruction of Alderis Prime to demonstrate the power of the Void Core. The planet was vaporized instantly, killing all 2 billion inhabitants.
""",
    "Dagobah_Minor.md": """# Dagobah Minor

## Overview
Dagobah Minor is a remote, swampy planet. It served as the exile home of Master Vexis.

## Geography
- Terrain: Swamps, bogs, dense forests
- Climate: Humid, misty, constant rain
""",
    "Nar_Shaddaa.md": """# Nar Shaddaa

## Overview
Nar Shaddaa, also known as the Smuggler's Moon, is a massive moon. A lawless haven for criminals.

## Zorak's Palace
Zorak the Crime Lord rules from a massive palace containing throne room, rancor pit, and vault.
""",
    "Zorak_Crime_Lord.md": """# Zorak the Crime Lord

## Overview
Zorak is a massive criminal mastermind who controls a vast criminal empire from his palace on Nar Shaddaa.

## Criminal Empire
- Controls Nar Shaddaa
- Employs bounty hunters
- Operates gambling casinos
""",
    "Vex_Hunter.md": """# Vex Hunter

## Overview
Vex Hunter is a notorious bounty hunter known for his distinctive Mandalorian armor.

## Equipment
- Mandalorian armor (beskar steel)
- Flame thrower
- Wrist rockets
- Jetpack
""",
    "Dax_Vonn.md": """# Dax Vonn

## Overview
Dax Vonn is a charismatic gambler, administrator of Aeros Station, and old friend of Jax Maverick.

## Aeros Station
Dax administers a mining colony floating in the atmosphere of Gas Giant Zephyra.
""",
    "Aeros_Station.md": """# Aeros Station

## Overview
Aeros Station, also known as Cloud City, is a tibanna gas mining facility floating in the atmosphere of Gas Giant Zephyra.

## Tibanna Gas Mining
Aeros Station mines tibanna gas, used in high-energy blaster power packs and hyperdrive fuel.
""",
    "Dusthaven.md": """# Dusthaven

## Overview
Dusthaven is a small settlement on Aridus Prime, known as a haven for smugglers and scavengers.

## The Cantina
Chalmun's Cantina is a notorious establishment where smugglers and bounty hunters gather.
"""
}

for filename, content in docs.items():
    with open(f"knowledge_base/{filename}", "w", encoding="utf-8") as f:
        f.write(content)

print(f"✅ Создано {len(docs)} документов!")
